version: "3"
services:
    app:
        container_name: app
        build: .
        depends_on:
            - db
        ports:
            - '80:80'
        env_file: .env
    db:
        container_name: database
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'laravel'
            MYSQL_USER: 'admin'
            MYSQL_PASSWORD: 'admin@123456'
            MYSQL_ROOT_PASSWORD: 'admin@123456'
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - my-db:/var/lib/mysql

volumes:
    my-db:
