version: "3.7"
services:
  db:
    image: mysql:5.7
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Master99
      MYSQL_DATABASE: usercontrol
      MYSQL_USER: Developer
      MYSQL_PASSWORD: Master99
  #web:
  #  image: "php:8.2-apache"
  #  container_name: php-container
  #  restart: always
  #  volumes:
  #    - ./usercontrol:/var/www/html
  #  ports:
  #   - "80:80"
  # depends_on:
  #    - db
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./usercontrol:/app
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    env_file:
      - ./usercontrol/.env.example
      - ./usercontrol/.env
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    working_dir: /app
    links:
      - db:db
    restart: always
    volumes:
      - ./usercontrol:/app
    depends_on:
       - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: Developer
      MYSQL_PASSWORD: Master99
      MYSQL_ROOT_PASSWORD: Master99